from __future__ import annotations

from typing import Protocol, Self, runtime_checkable

from nttl.hal.types import CameraInfo, ControlRange, Frame, Roi


@runtime_checkable
class Camera(Protocol):
    @property
    def info(self) -> CameraInfo: ...

    @property
    def is_open(self) -> bool: ...

    def open(self) -> None: ...

    def close(self) -> None: ...

    def controls(self) -> dict[str, ControlRange]: ...

    def get_control(self, name: str) -> float: ...

    def set_control(self, name: str, value: float) -> None: ...

    def get_roi(self) -> Roi: ...

    def set_roi(self, roi: Roi) -> None: ...

    def expose(self, exposure_s: float, *, dark: bool = False) -> Frame: ...

    def set_cooler(self, *, enabled: bool, target_c: float | None = None) -> None: ...

    def __enter__(self) -> Self: ...

    def __exit__(self, *exc: object) -> None: ...
